{% set name = "dask-yarn" %}
{% set version = "0.9" %}
{% set pkg_loc = "py2.py3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/{{ pkg_loc }}/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-{{ pkg_loc }}-none-any.whl

build:
  number: 0
  skip: true  # [win or py<35]
  entry_points:
    - dask-yarn=dask_yarn.cli:main
  script:
    - python -m pip install --no-deps --ignore-installed {{ name }}-{{ version }}-{{ pkg_loc }}-none-any.whl
    - cp {{ SP_DIR }}/{{ name }}-{{ version }}.dist-info/LICENSE.txt {{ SRC_DIR }}/LICENSE.txt

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dask-core >=2021.1.0
    - distributed >=2021.1.0
    - skein >=0.8.1
    - grpcio >=1.14.0

test:
  imports:
    - dask_yarn
  commands:
    - dask-yarn --help

about:
  home: https://github.com/dask/dask-yarn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Deploy dask clusters on Apache YARN
  description: |
    Dask-Yarn deploys Dask on YARN clusters, such as are found in traditional
    Hadoop installations. Dask-Yarn provides an easy interface to quickly
    start, stop, and scale Dask clusters natively from Python.
  doc_url: https://dask-yarn.readthedocs.io/
  dev_url: https://github.com/dask/dask-yarn

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - quasiben
