{% set name = "dask-yarn" %}
{% set pkg_name = "dask_yarn" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e533be8ae0b1d46c7e916e50506a2b039de8d84a1590c705ad4166dda292623e

build:
  number: 0
  skip: true  # [win or py<35]
  entry_points:
    - dask-yarn=dask_yarn.cli:main
  script:
    - python -m pip install --no-deps --ignore-installed {{ pkg_name }}-{{ version }}-py3-none-any.whl
    - cp {{ SP_DIR }}/{{ name }}-{{ version }}.dist-info/LICENSE.txt {{ SRC_DIR }}/LICENSE.txt

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dask-core >=2021.1.0
    - distributed >=2021.1.0
    - skein >=0.8.1
    - grpcio >=1.14.0

test:
  imports:
    - dask_yarn
  commands:
    - dask-yarn --help

about:
  home: https://github.com/dask/dask-yarn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Deploy dask clusters on Apache YARN
  description: |
    Dask-Yarn deploys Dask on YARN clusters, such as are found in traditional
    Hadoop installations. Dask-Yarn provides an easy interface to quickly
    start, stop, and scale Dask clusters natively from Python.
  doc_url: https://dask-yarn.readthedocs.io/
  dev_url: https://github.com/dask/dask-yarn

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - quasiben
