{% set name = "dask-yarn" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5651d49deafa73702f12a74b5c6c055e7b4492921094b297b13d1aa2420c89fa

build:
  number: 0
  skip: True  # [win]
  entry_points:
    - dask-yarn=dask_yarn.cli:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dask >=0.19.0
    - distributed >=1.23.0
    - skein >=0.5.0
    - grpcio >=1.14.0
    - backports.weakref  # [py2k]

test:
  imports:
    - dask_yarn
  commands:
    - dask-yarn --help

about:
  home: https://github.com/dask/dask-yarn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Deploy dask clusters on Apache YARN
  description: |
    Dask-Yarn deploys Dask on YARN clusters, such as are found in traditional
    Hadoop installations. Dask-Yarn provides an easy interface to quickly
    start, stop, and scale Dask clusters natively from Python.
  doc_url: https://dask-yarn.readthedocs.io/
  dev_url: https://github.com/dask/dask-yarn

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
