travis:
  secure:
    BINSTAR_TOKEN: dmSvWfG/w7x6n/pbOIne6jyZy6hMuI970wOvcb8TlY3NDkqdvAT16b5z0hCBBj3q3iORpQGxTzk+wjiOUam+HKIeFgvlnSVHz0iXektTO/w1o99Nfj4X3b8vKqZiO/R9E7JP4ClO4+jpDBpU4l4l7cbfQZ5BduevmCbJL8F6mL9Gd1Vk6mfAphc41DMTlU4y+85j6x9/OdyIvTbozXE9it2xmg28WKMi+3jzsngnOMsHSj2jhOSgtDeQfT+U/VEQyFAXV93EwfbZ64AFYM75Xk2XfLIOUGOCrPgp7mEZDVynmY3Q72WHC+L0OMu9SzVo9OZGiIOfh0GbsUekUFeIRa6TVtJQIHaqhbYwWKn+Ej1gWzju7JP0X9bRQJTdOTGVYk4HWtc6Z6jaSzzv4rJ6vooNwvcLXun++H64GsSDbUxln0w8Opgpyakb4Iq63ln/EE25j9TBmrWC6EB0evCyXpoENoujefJR+dsObNsosWLHzSksmYw9YctzBuBCYB3h5vJoYNGoJqgnRxkAG8QL1NpgT6h8valU2uSCP/4r8/h9Sdlvp23xZqwPsxkaCTwB4UiATEIRtmTOw9+MaSRqh6KE1MUtUj76Dnxua89fW7FI1lF9XOFw4Sc2LsUJvBz7wGn3HJNn7pzZvIAAH5pgSs4sRoQrZXsHWVLmhY5k808=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
